### PR TITLE
Implemented Login and Register feature

### PR DESCRIPTION
**Pull request by judgegodwins**
Implemented register feat at API endpoint /api/register, also checks for email validity first.
Screenshot from 2020-06-09 05-49-56

Implemented login feat at API endpoint /api/login
Screenshot from 2020-06-09 05-53-40

Implemented reset password feature at API endpoint /api/reset-password
Screenshot from 2020-06-09 05-54-29

`express-session` was also used for sessions. Sessions are stored in mongodb with connect-mongo. 
Cookie maxAge set to 15 days ( Users can stay logged in for 15 days.)

### CODE REVIEW

**Comment by iAmServer** [comment]
Hello, the login and register as been implemented, can you work on the reset-password based on what project structure

**Comment by judgegodwins** [comment]
You guys used jwt right. Is there a way to get the users object from the request object. Like `req.user` as is done when using passport

**Comment by judgegodwins** [comment]
> Hello, the login and register as been implemented, can you work on the reset-password based on what project structure

You guys used jwt right? Is there a way to get the users object from the request object. Like req.user as is done when using passport

**Comment by judgegodwins** [comment]
> > Hello, the login and register as been implemented, can you work on the reset-password based on what project structure
> 
> You guys used jwt right? Is there a way to get the users object from the request object. Like req.user as is done when using passport

I have already handled reset password in my PR using the `req.user` object

**Comment by iAmServer** [comment]
Use the model to get user email after verifying the token is valid

**Comment by judgegodwins** [comment]
Can i implement the google authentication

**Comment by iAmServer** [comment]
Yes you can

Sent from my T-Mobile 4G LTE Device

________________________________

**Pull request closed without merging**
