### PR TITLE
Docker setup with single /api/hello route

### PR DESCRIPTION
**Pull request by olaysco**
### What does this PR do?
- This PR setup the project with babel and nodemon for development
- It orchestrates the project with Docker and docker-compose for production deployment

### How should this be manually tested?
- for docker test, ensure you have Docker engine installed on your machine, in the root of the folder run `docker-compose up` once setup is complete point postman or  api testing tool to **http://localhost:81/api/hello**

- for development test run `npm install` to install dependencies and `npm run dev-start` to start development. 

**please note that nodemon is required for development for hot update**

### Screenshots
image

image

### CODE REVIEW

**Review by iAmServer — COMMENTED** [review]
For which service is this?

**Comment by olaysco** [comment]
Service?

**Comment by olaysco** [comment]
Its just general docker setup with node, before we start working on individual endpoints

**Comment by olaysco** [comment]
If we don't have this first,  I believe it would be hard for people to know where and how to contribute

**Review by t-ame — APPROVED** [review]
This is very useful. I believe this should be merged so we can all start working.

**Pull request merged**
